services:
  conviniencer:
    build: .
    networks:
      - conviniencer

  mongo:
    image: mongo
    networks:
      conviniencer:
        aliases:
          - mongo
    volumes:
      - type: volume
        source: mongo
        target: /data/db
      - type: bind
        source: ./indexes.js
        target: /docker-entrypoint-initdb.d/indexes.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}


networks:
  conviniencer:
    driver: bridge


volumes:
  mongo:
